static_resources:

  listeners:
  - address:
      socket_address:
        address: 127.0.0.1
        port_value: 19092
    filter_chains:
    - filters:
      # Just metrics.
      - name: envoy.filters.network.kafka_broker
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.kafka_broker.v3.KafkaBroker
          stat_prefix: exampleprefix
      # Real work.
      - name: envoy.filters.network.kafka_mesh
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.kafka_mesh.v3alpha.KafkaMesh
          advertised_host: "127.0.0.1"
          advertised_port: 19092
          upstream_clusters:
          - cluster_name: kafka_c1
            bootstrap_servers: 127.0.0.1:9092
            partition_count: 1
          - cluster_name: kafka_c2
            bootstrap_servers: 127.0.0.1:9093
            partition_count: 1
          - cluster_name: kafka_c3
            bootstrap_servers: 127.0.0.1:9094
            partition_count: 5
            producer_config:
              acks: "1"
              linger.ms: "500"

          forwarding_rules:
          - target_cluster: kafka_c1
            topic_prefix: a
          - target_cluster: kafka_c2
            topic_prefix: b
          - target_cluster: kafka_c3
            topic_prefix: c

admin:
  access_log_path: /dev/null
  profile_path: /dev/null
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }
